FROM php:8.1-fpm

RUN apt-get update && apt-get install -y git curl libxml2-dev libonig-dev libpng-dev zip unzip libzip-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /home/app/

EXPOSE 8000

USER $user

CMD composer install && php artisan serve --host=0.0.0.0 --port=8000
