# Usar Node.js como imagen base
FROM node:18

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos necesarios para instalar las dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar todo el código fuente al contenedor
COPY . .

# Exponer el puerto que usa Angular CLI para desarrollo
EXPOSE 4200

# Comando por defecto para iniciar el servidor de desarrollo
CMD ["npm", "run", "start"]
